name: chaleno
description: A package to web scraping data from websites easily and faster using less code lines.
version: 0.0.6
homepage: https://github.com/antonio-nicolau/chaleno

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter